use std::sync::Arc;

use fluorite_codegen::code_gen::fs::MemoryFileSystem;
use fluorite_codegen::code_gen::go::{GoOptions, GoTemplateGenerator};
use fluorite_codegen::code_gen::ir::{IRFieldType, IRPrimitive, IRSchema, IRTypeRef};

fn generator(options: GoOptions) -> (GoTemplateGenerator, Arc<MemoryFileSystem>) {
    let fs = Arc::new(MemoryFileSystem::new());
    (GoTemplateGenerator::new(options, fs.clone()), fs)
}

#[test]
fn package_name_defaults_to_the_output_directory_basename() {
    let options = GoOptions::new("./examples/demo-go/generated".to_string());
    assert_eq!(options.resolved_package_name(), "generated");
}

#[test]
fn package_name_override_wins() {
    let options = GoOptions::new("./out".to_string()).with_package_name("demo");
    assert_eq!(options.resolved_package_name(), "demo");
}

#[test]
fn package_name_is_sanitised_for_go() {
    let options = GoOptions::new("./demo-go".to_string());
    assert_eq!(options.resolved_package_name(), "demo_go");
}

#[test]
fn primitives_map_to_stdlib_go_types() {
    let (generator, _fs) = generator(GoOptions::new("./out".to_string()));
    assert_eq!(generator.format_primitive(IRPrimitive::String), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::Bool), "bool");
    assert_eq!(generator.format_primitive(IRPrimitive::UInt64), "uint64");
    assert_eq!(generator.format_primitive(IRPrimitive::Float32), "float32");
    assert_eq!(generator.format_primitive(IRPrimitive::UUID), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::Decimal), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::Bytes), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::Url), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::DateTime), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::Duration), "string");
    assert_eq!(generator.format_primitive(IRPrimitive::Timestamp), "int64");
    assert_eq!(
        generator.format_primitive(IRPrimitive::TimestampMillis),
        "int64"
    );
}

#[test]
fn collections_and_any_format_as_go_types() {
    let (generator, _fs) = generator(GoOptions::new("./out".to_string()));
    let schema = IRSchema {
        packages: std::collections::BTreeMap::new(),
    };

    let list = IRFieldType::List(Box::new(IRFieldType::Primitive(IRPrimitive::String)));
    assert_eq!(generator.format_type(&list, &schema).unwrap(), "[]string");

    let map = IRFieldType::Map(
        Box::new(IRFieldType::Primitive(IRPrimitive::String)),
        Box::new(IRFieldType::Custom(IRTypeRef::new("demo", "Order"))),
    );
    assert_eq!(
        generator.format_type(&map, &schema).unwrap(),
        "map[string]Order"
    );

    assert_eq!(
        generator.format_type(&IRFieldType::Any, &schema).unwrap(),
        "any"
    );
}

use fluorite_codegen::code_gen::ir::{
    IREnum, IREnumVariant, IRField, IRPackage, IRStruct, IRType, IRTypeAlias, IRTypeAliasTarget,
};

fn field(name: &str, ty: IRFieldType, optional: bool, doc: Option<&str>) -> IRField {
    IRField {
        name: name.to_string(),
        field_type: ty,
        is_optional: optional,
        is_boxed: false,
        rename: None,
        doc: doc.map(|d| d.to_string()),
        alias: Vec::new(),
        default: None,
        skip_if_none: false,
        skip_if_default: false,
        flatten: false,
        deprecated: false,
    }
}

fn schema_of(package: &str, types: Vec<IRType>) -> IRSchema {
    let mut packages = std::collections::BTreeMap::new();
    packages.insert(
        package.to_string(),
        IRPackage {
            name: package.to_string(),
            types,
        },
    );
    IRSchema { packages }
}

#[test]
fn generates_a_struct_with_aligned_fields_and_json_tags() {
    let s = IRStruct {
        name: "AgentView".to_string(),
        doc: Some("An agent preset as shown to clients.".to_string()),
        deny_unknown_fields: false,
        fields: vec![
            field(
                "id",
                IRFieldType::Primitive(IRPrimitive::UInt64),
                false,
                None,
            ),
            field(
                "model_id",
                IRFieldType::Primitive(IRPrimitive::String),
                false,
                None,
            ),
            field(
                "thinking_effort",
                IRFieldType::Primitive(IRPrimitive::String),
                true,
                None,
            ),
        ],
    };
    let schema = schema_of("demo", vec![IRType::Struct(s)]);
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    let content = fs.get_string("out/agent_view.go").unwrap();
    assert_eq!(
        content,
        "// Code generated by fluorite. DO NOT EDIT.\n\
         \n\
         package demo\n\
         \n\
         // An agent preset as shown to clients.\n\
         type AgentView struct {\n\
         \tID             uint64  `json:\"id\"`\n\
         \tModelID        string  `json:\"modelId\"`\n\
         \tThinkingEffort *string `json:\"thinkingEffort,omitempty\"`\n\
         }\n"
    );
}

#[test]
fn a_documented_field_starts_a_new_alignment_run() {
    let s = IRStruct {
        name: "Mixed".to_string(),
        doc: None,
        deny_unknown_fields: false,
        fields: vec![
            field(
                "id",
                IRFieldType::Primitive(IRPrimitive::String),
                false,
                None,
            ),
            field(
                "long_field_name",
                IRFieldType::Primitive(IRPrimitive::Bool),
                false,
                Some("Documented."),
            ),
        ],
    };
    let schema = schema_of("demo", vec![IRType::Struct(s)]);
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    let content = fs.get_string("out/mixed.go").unwrap();
    assert!(content.contains("\tID string `json:\"id\"`\n"), "{content}");
    assert!(
        content.contains("\t// Documented.\n\tLongFieldName bool `json:\"longFieldName\"`\n"),
        "{content}"
    );
}

#[test]
fn generates_an_enum_as_a_string_type_with_aligned_constants() {
    let e = IREnum {
        name: "UserStatus".to_string(),
        variants: vec![IREnumVariant::new("Active"), IREnumVariant::new("Inactive")],
        doc: None,
    };
    let schema = schema_of("demo", vec![IRType::Enum(e)]);
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    let content = fs.get_string("out/user_status.go").unwrap();
    assert!(content.contains("type UserStatus string\n"), "{content}");
    assert!(
        content.contains(
            "const (\n\
             \tUserStatusActive   UserStatus = \"Active\"\n\
             \tUserStatusInactive UserStatus = \"Inactive\"\n\
             )\n"
        ),
        "{content}"
    );
}

#[test]
fn generates_type_aliases_for_lists_and_maps() {
    let list = IRTypeAlias {
        name: "UserList".to_string(),
        target: IRTypeAliasTarget::List(IRFieldType::Custom(IRTypeRef::new("demo", "User"))),
        doc: None,
    };
    let map = IRTypeAlias {
        name: "OrderMap".to_string(),
        target: IRTypeAliasTarget::Map(
            IRFieldType::Primitive(IRPrimitive::String),
            IRFieldType::Custom(IRTypeRef::new("demo", "Order")),
        ),
        doc: None,
    };
    // The validator rejects references to types the schema does not define, so
    // the aliases' targets have to exist.
    let user = IRStruct {
        name: "User".to_string(),
        doc: None,
        deny_unknown_fields: false,
        fields: vec![field(
            "id",
            IRFieldType::Primitive(IRPrimitive::String),
            false,
            None,
        )],
    };
    let order = IRStruct {
        name: "Order".to_string(),
        doc: None,
        deny_unknown_fields: false,
        fields: vec![field(
            "id",
            IRFieldType::Primitive(IRPrimitive::String),
            false,
            None,
        )],
    };
    let schema = schema_of(
        "demo",
        vec![
            IRType::Struct(user),
            IRType::Struct(order),
            IRType::TypeAlias(list),
            IRType::TypeAlias(map),
        ],
    );
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    assert!(fs
        .get_string("out/user_list.go")
        .unwrap()
        .contains("type UserList []User\n"));
    assert!(fs
        .get_string("out/order_map.go")
        .unwrap()
        .contains("type OrderMap map[string]Order\n"));
}

#[test]
fn single_file_mode_emits_one_file_with_one_package_clause() {
    let s = IRStruct {
        name: "A".to_string(),
        doc: None,
        deny_unknown_fields: false,
        fields: vec![field(
            "x",
            IRFieldType::Primitive(IRPrimitive::Bool),
            false,
            None,
        )],
    };
    let e = IREnum {
        name: "B".to_string(),
        variants: vec![IREnumVariant::new("One")],
        doc: None,
    };
    let schema = schema_of("demo", vec![IRType::Struct(s), IRType::Enum(e)]);
    let (generator, fs) = generator(
        GoOptions::new("out".to_string())
            .with_package_name("demo")
            .with_single_file(true),
    );
    generator.generate_from_schema(&schema).unwrap();

    let content = fs.get_string("out/types.go").unwrap();
    assert_eq!(content.matches("package demo").count(), 1);
    assert!(content.contains("type A struct {"), "{content}");
    assert!(content.contains("type B string"), "{content}");
}

#[test]
fn rejects_a_type_name_used_in_two_packages() {
    let mut packages = std::collections::BTreeMap::new();
    for pkg in ["demo.users", "demo.orders"] {
        packages.insert(
            pkg.to_string(),
            IRPackage {
                name: pkg.to_string(),
                types: vec![IRType::Enum(IREnum {
                    name: "Status".to_string(),
                    variants: vec![IREnumVariant::new("On")],
                    doc: None,
                })],
            },
        );
    }
    let schema = IRSchema { packages };
    let (generator, _fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));

    let err = generator
        .generate_from_schema(&schema)
        .unwrap_err()
        .to_string();
    assert!(err.contains("Status"), "{err}");
    assert!(err.contains("demo.users"), "{err}");
    assert!(err.contains("demo.orders"), "{err}");
}

#[test]
fn rejects_unsupported_field_attributes() {
    let mut f = field(
        "meta",
        IRFieldType::Primitive(IRPrimitive::String),
        false,
        None,
    );
    f.flatten = true;
    let s = IRStruct {
        name: "Flat".to_string(),
        doc: None,
        deny_unknown_fields: false,
        fields: vec![f],
    };
    let schema = schema_of("demo", vec![IRType::Struct(s)]);
    let (generator, _fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));

    let err = generator
        .generate_from_schema(&schema)
        .unwrap_err()
        .to_string();
    assert!(err.contains("flatten"), "{err}");
    assert!(err.contains("Flat"), "{err}");
    assert!(err.contains("meta"), "{err}");
}

#[test]
fn rejects_deny_unknown_fields() {
    let s = IRStruct {
        name: "Strict".to_string(),
        doc: None,
        deny_unknown_fields: true,
        fields: vec![field(
            "x",
            IRFieldType::Primitive(IRPrimitive::Bool),
            false,
            None,
        )],
    };
    let schema = schema_of("demo", vec![IRType::Struct(s)]);
    let (generator, _fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));

    let err = generator
        .generate_from_schema(&schema)
        .unwrap_err()
        .to_string();
    assert!(err.contains("deny_unknown_fields"), "{err}");
    assert!(err.contains("Strict"), "{err}");
}

use fluorite_codegen::code_gen::ir::{IRUnion, IRUnionVariant};

#[test]
fn generates_a_union_as_a_sealed_interface_wrapper() {
    let user = IRStruct {
        name: "User".to_string(),
        doc: None,
        deny_unknown_fields: false,
        fields: vec![field(
            "id",
            IRFieldType::Primitive(IRPrimitive::String),
            false,
            None,
        )],
    };
    let u = IRUnion {
        name: "UserEvent".to_string(),
        tag_field: "type".to_string(),
        content_field: "value".to_string(),
        doc: None,
        variants: vec![
            IRUnionVariant::Newtype {
                name: "Created".to_string(),
                ty: IRFieldType::Custom(IRTypeRef::new("demo", "User")),
                doc: None,
            },
            IRUnionVariant::Unit {
                name: "Deleted".to_string(),
                doc: None,
            },
            IRUnionVariant::Newtype {
                name: "Renamed".to_string(),
                ty: IRFieldType::Primitive(IRPrimitive::String),
                doc: None,
            },
        ],
    };
    let schema = schema_of("demo", vec![IRType::Struct(user), IRType::Union(u)]);
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    let content = fs.get_string("out/user_event.go").unwrap();

    assert!(
        content.contains("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n"),
        "{content}"
    );
    assert!(
        content.contains("type UserEventVariant interface {\n\tisUserEventVariant()\n}\n"),
        "{content}"
    );
    assert!(
        content.contains("type UserEventCreated struct {\n\tValue User\n}\n"),
        "{content}"
    );
    assert!(
        content.contains("func (UserEventCreated) isUserEventVariant() {}\n"),
        "{content}"
    );
    assert!(
        content.contains("type UserEventDeleted struct{}\n"),
        "{content}"
    );
    assert!(
        content.contains("type UserEventRenamed struct {\n\tValue string\n}\n"),
        "{content}"
    );
    assert!(
        content.contains("type UserEvent struct {\n\tVariant UserEventVariant\n}\n"),
        "{content}"
    );
    assert!(
        content.contains("\tcase UserEventCreated:\n\t\treturn json.Marshal(struct {\n\t\t\tType  string `json:\"type\"`\n\t\t\tValue User   `json:\"value\"`\n\t\t}{\"Created\", v.Value})\n"),
        "{content}"
    );
    assert!(
        content.contains("\tcase UserEventDeleted:\n\t\treturn json.Marshal(struct {\n\t\t\tType string `json:\"type\"`\n\t\t}{\"Deleted\"})\n"),
        "{content}"
    );
    assert!(
        content.contains(
            "\tcase nil:\n\t\treturn nil, fmt.Errorf(\"fluorite: UserEvent has no variant set\")\n"
        ),
        "{content}"
    );
    assert!(
        content.contains(
            "\t\tType  string          `json:\"type\"`\n\t\tValue json.RawMessage `json:\"value\"`\n"
        ),
        "{content}"
    );
    assert!(
        content.contains("\t\tu.Variant = UserEventDeleted{}\n"),
        "{content}"
    );
    assert!(
        content.contains(
            "return fmt.Errorf(\"fluorite: unknown UserEvent variant tag %q\", envelope.Type)\n"
        ),
        "{content}"
    );
}

#[test]
fn honours_a_custom_type_tag() {
    let u = IRUnion {
        name: "Outcome".to_string(),
        tag_field: "kind".to_string(),
        content_field: "payload".to_string(),
        doc: None,
        variants: vec![IRUnionVariant::Unit {
            name: "Ok".to_string(),
            doc: None,
        }],
    };
    let schema = schema_of("demo", vec![IRType::Union(u)]);
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    let content = fs.get_string("out/outcome.go").unwrap();
    assert!(content.contains("`json:\"kind\"`"), "{content}");
    assert!(content.contains("`json:\"payload\"`"), "{content}");
}

#[test]
fn multi_line_docs_survive_on_types_fields_and_variants() {
    let s = IRStruct {
        name: "Doc".to_string(),
        doc: Some("Summary line.\n\nDetail line.".to_string()),
        deny_unknown_fields: false,
        fields: vec![field(
            "id",
            IRFieldType::Primitive(IRPrimitive::String),
            false,
            Some("First.\nSecond."),
        )],
    };
    let e = IREnum {
        name: "Kind".to_string(),
        doc: None,
        variants: vec![IREnumVariant {
            name: "One".to_string(),
            doc: Some("The only one.".to_string()),
        }],
    };
    let u = IRUnion {
        name: "Evt".to_string(),
        tag_field: "type".to_string(),
        content_field: "value".to_string(),
        doc: Some("An event.".to_string()),
        variants: vec![IRUnionVariant::Unit {
            name: "Gone".to_string(),
            doc: Some("It went away.".to_string()),
        }],
    };
    let schema = schema_of(
        "demo",
        vec![IRType::Struct(s), IRType::Enum(e), IRType::Union(u)],
    );
    let (generator, fs) = generator(GoOptions::new("out".to_string()).with_package_name("demo"));
    generator.generate_from_schema(&schema).unwrap();

    // A blank doc line becomes a bare `//`, never `// ` with trailing space.
    let doc_go = fs.get_string("out/doc.go").unwrap();
    assert!(
        doc_go.contains("// Summary line.\n//\n// Detail line.\ntype Doc struct {\n"),
        "{doc_go}"
    );
    assert!(
        doc_go.contains("\t// First.\n\t// Second.\n\tID string `json:\"id\"`\n"),
        "{doc_go}"
    );

    let kind_go = fs.get_string("out/kind.go").unwrap();
    assert!(
        kind_go.contains("const (\n\t// The only one.\n\tKindOne Kind = \"One\"\n)\n"),
        "{kind_go}"
    );

    let evt_go = fs.get_string("out/evt.go").unwrap();
    assert!(
        evt_go.contains("// It went away.\ntype EvtGone struct{}\n"),
        "{evt_go}"
    );
    assert!(
        evt_go.contains("// An event.\n// Evt is an adjacently tagged union"),
        "{evt_go}"
    );
}
